version: '3.8'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:8080
      - 443:443
    networks:
      - app_network
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: db
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
    networks:
      - app_network
    ports:
      - 1433:1433

volumes:
  sqlserver_data:
networks:
  app_network:
    driver: bridge
